import pandas as pd
import numpy as np

# Load the full results and properties
results_path = "outputs/csvs/allcfa_results.csv"
props_path = "data/spectra_properties.csv"

df = pd.read_csv(results_path)
props = pd.read_csv(props_path)

# Merge to get SNR and Subtype
df = df.merge(props[['Filename', 'SNR', 'Subtype']], left_on='filename', right_on='Filename', how='left')

# Calculate absolute residual for Nuisance method
# nuis_res is already (nuis_age - true_age) in the CSV if it was generated by analyze_cfa_results.py
# If not, we calculate it here
if 'nuis_res' not in df.columns:
    df['nuis_res'] = df['nuis_age'] - df['true_age']

df['abs_nuis_res'] = df['nuis_res'].abs()

# Sort by absolute residual descending
outliers = df.sort_values('abs_nuis_res', ascending=False).head(15)

# Select relevant columns for display
cols = ['filename', 'true_age', 'nuis_age', 'nuis_res', 'SNR', 'Subtype']
print("Top 15 Spectra with the Greatest Absolute Residuals (Nuisance Method):")
print(outliers[cols].to_string(index=False))
